version: "3.9"
services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: txwell
      POSTGRES_PASSWORD: txwell
      POSTGRES_DB: txwell
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./apps/api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      CORS_ORIGINS: ${CORS_ORIGINS}
    volumes:
      - ./apps/api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  web:
    build: ./apps/web
    environment:
      PUBLIC_API_URL: ${PUBLIC_API_URL}
    volumes:
      - ./apps/web:/app
    ports:
      - "4321:4321"
    depends_on:
      - api
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","4321"]

  worker:
    build: ./apps/worker
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./apps/worker:/app
      - ./data-pipeline:/data-pipeline
    depends_on:
      - db
      - redis

volumes:
  pgdata: