name: API Smoke (P2)

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: api-smoke
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, staging, prod]
        include:
          - env: dev
            base: https://api.dev.txwelllookup.com
          - env: staging
            base: https://api.staging.txwelllookup.com
          - env: prod
            base: https://api.txwelllookup.com
    steps:
      - name: Health (${{ matrix.env }})
        run: |
          set -euo pipefail
          code=$(curl -sS -o /dev/null -w '%{http_code}' "$BASE/health")
          echo "health_status=$code" >> "$GITHUB_OUTPUT"
          test "$code" = "200"
        env:
          BASE: ${{ matrix.base }}
      - name: Preflight CORS (${{ matrix.env }})
        run: |
          curl -sS -i -X OPTIONS \
            -H "Origin: https://www.txwelllookup.com" \
            -H "Access-Control-Request-Method: GET" \
            "$BASE/v1/search" | head -20 || true
        env:
          BASE: ${{ matrix.base }}


