name: CI Smoke (DB)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  db-smoke:
    name: Database connectivity and sanity checks
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Run smoke checks
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python scripts/ci_smoke_db.py --database-url "$DATABASE_URL"

      - name: Compute SDR as-of date (info)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python ground_truth/tools/compute_as_of.py --database-url "$DATABASE_URL" --schema ground_truth --out docs/AS_OF.md
          echo "As-of file updated (not committing in this workflow)"


