name: DB Apply & Verify (P1)

on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment to target
        required: true
        default: dev
        type: choice
        options: [dev, staging, prod]

permissions:
  contents: read

concurrency:
  group: db-apply-${{ inputs.env }}
  cancel-in-progress: true

jobs:
  apply:
    name: Apply schema (${{ inputs.env }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup psql container
        run: |
          docker pull postgres:15
      - name: Sanitize connection string
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          DB_URL="$DATABASE_URL"
          # Strip accidental leading 'psql ' if user pasted full CLI command
          DB_URL="${DB_URL#psql }"
          DB_URL="${DB_URL#psql}"
          # Remove surrounding single/double quotes
          DB_URL="${DB_URL%\'}"; DB_URL="${DB_URL#\'}"
          DB_URL="${DB_URL%\"}"; DB_URL="${DB_URL#\"}"
          echo "CONNECT_URL=$DB_URL" >> "$GITHUB_ENV"
      - name: Enable extensions
        run: |
          docker run --rm postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -c "CREATE EXTENSION IF NOT EXISTS postgis;"
          docker run --rm postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
      - name: Apply base schema
        run: |
          docker run --rm -v "$GITHUB_WORKSPACE:/work" -w /work postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -f db/init/01_postgis.sql
          # Prefer full GWDB schema; fall back to links-only if present
          (docker run --rm -v "$GITHUB_WORKSPACE:/work" -w /work postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -f db/init/02_gwdb.sql) || (docker run --rm -v "$GITHUB_WORKSPACE:/work" -w /work postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -f db/init/02_gwdb_links.sql)
          docker run --rm -v "$GITHUB_WORKSPACE:/work" -w /work postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -f db/init/03_well_reports_fix.sql
          # Optional: RRC schema used by /v1/energy/nearby
          (docker run --rm -v "$GITHUB_WORKSPACE:/work" -w /work postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -f db/init/03_rrc.sql) || true
          # Optional indexes if present
          (docker run --rm -v "$GITHUB_WORKSPACE:/work" -w /work postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -f db/init/04_indexes.sql) || true
          # Optional alerts tables if present
          (docker run --rm -v "$GITHUB_WORKSPACE:/work" -w /work postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -f db/init/04_alerts.sql) || true

  verify:
    name: Verify schema (${{ inputs.env }})
    runs-on: ubuntu-latest
    needs: apply
    environment: ${{ inputs.env }}
    steps:
      - name: Setup psql container
        run: |
          docker pull postgres:15
      - name: Sanitize connection string
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          DB_URL="$DATABASE_URL"
          DB_URL="${DB_URL#psql }"; DB_URL="${DB_URL#psql}"
          DB_URL="${DB_URL%\'}"; DB_URL="${DB_URL#\'}"
          DB_URL="${DB_URL%\"}"; DB_URL="${DB_URL#\"}"
          echo "CONNECT_URL=$DB_URL" >> "$GITHUB_ENV"
      - name: Verify extensions
        run: |
          docker run --rm postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -c "SELECT extname FROM pg_extension WHERE extname IN ('postgis','pg_trgm');"
      - name: Verify core tables exist
        run: |
          docker run --rm postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -c "SELECT 'well_reports' AS tbl, to_regclass('public.well_reports') IS NOT NULL AS exists
          UNION ALL SELECT 'gwdb_wells', to_regclass('public.gwdb_wells') IS NOT NULL
          UNION ALL SELECT 'well_links', to_regclass('public.well_links') IS NOT NULL
          UNION ALL SELECT 'rrc_permits', to_regclass('public.rrc_permits') IS NOT NULL
          UNION ALL SELECT 'rrc_wellbores', to_regclass('public.rrc_wellbores') IS NOT NULL;"
      - name: Show indexes summary
        run: |
          docker run --rm postgres:15 psql "$CONNECT_URL" -v ON_ERROR_STOP=1 -c "SELECT tablename, indexname FROM pg_indexes WHERE schemaname='public' AND tablename IN ('well_reports','gwdb_wells') ORDER BY tablename, indexname;"
