name: Apply DB Init (DS2)

on:
  workflow_dispatch:
    inputs:
      env:
        description: Which environment's secrets to use (dev|staging|prod)
        required: false
        default: prod
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read

concurrency:
  group: db-apply-${{ inputs.env }}
  cancel-in-progress: false

jobs:
  apply:
    name: Apply SQL init files (${{ inputs.env }})
    runs-on: ubuntu-latest
    environment: ${{ (inputs.env != '' && inputs.env) || 'prod' }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      RAW_SDR_BUCKET: ${{ vars.RAW_SDR_BUCKET }}
      RAW_SDR_PREFIX: ${{ vars.RAW_SDR_PREFIX }}
      STORAGE_ACCESS_KEY_ID: ${{ secrets.STORAGE_ACCESS_KEY_ID }}
      STORAGE_SECRET_ACCESS_KEY: ${{ secrets.STORAGE_SECRET_ACCESS_KEY }}
      STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends postgresql-client

      - name: Check DB connectivity
        run: |
          if [ -z "${DATABASE_URL:-}" ]; then echo "DATABASE_URL is not set" >&2; exit 2; fi
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "select version();"

      - name: Install AWS CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends awscli

      - name: Fetch latest raw SDR schema from R2 (if available)
        run: |
          set -euo pipefail
          mkdir -p data/tmp
          if [ -z "${RAW_SDR_BUCKET:-}" ] || [ -z "${RAW_SDR_PREFIX:-}" ]; then
            echo "RAW_SDR_BUCKET/RAW_SDR_PREFIX not set; skipping raw schema fetch"
            exit 0
          fi
          export AWS_ACCESS_KEY_ID="$STORAGE_ACCESS_KEY_ID"
          export AWS_SECRET_ACCESS_KEY="$STORAGE_SECRET_ACCESS_KEY"
          export AWS_DEFAULT_REGION="auto"
          SNAPSHOTS_PREFIX="$RAW_SDR_PREFIX/snapshots/"
          echo "Listing snapshots under s3://$RAW_SDR_BUCKET/$SNAPSHOTS_PREFIX"
          LATEST=$(aws s3 ls "s3://$RAW_SDR_BUCKET/$SNAPSHOTS_PREFIX" --endpoint-url "$STORAGE_ENDPOINT" | awk '{print $NF}' | sed 's#/##' | sort | tail -n 1 || true)
          if [ -z "${LATEST:-}" ]; then
            echo "No snapshots found; skipping raw schema fetch"
            exit 0
          fi
          SRC="s3://$RAW_SDR_BUCKET/$SNAPSHOTS_PREFIX$LATEST/sdr_raw_schema.sql"
          echo "Fetching $SRC"
          aws s3 cp "$SRC" data/tmp/sdr_raw_schema.sql --endpoint-url "$STORAGE_ENDPOINT" || true
          if [ -s data/tmp/sdr_raw_schema.sql ]; then
            echo "Raw schema downloaded: data/tmp/sdr_raw_schema.sql"
          else
            echo "Raw schema not present in latest snapshot; continuing"
          fi

      - name: Apply 01_postgis.sql
        run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/init/01_postgis.sql

      - name: Apply 03_well_reports_fix.sql
        run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/init/03_well_reports_fix.sql

      - name: Apply raw SDR schema (if downloaded)
        run: |
          if [ -s data/tmp/sdr_raw_schema.sql ]; then psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f data/tmp/sdr_raw_schema.sql; else echo "No raw schema file to apply"; fi

      - name: Apply 03_sdr_children.sql (DS2)
        run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/init/03_sdr_children.sql

      - name: Apply 04_indexes.sql (optional)
        run: |
          if [ -f db/init/04_indexes.sql ]; then psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/init/04_indexes.sql; fi

      - name: Apply 04_alerts.sql (optional)
        run: |
          if [ -f db/init/04_alerts.sql ]; then psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/init/04_alerts.sql; fi

      - name: Job summary
        run: |
          echo "### DB Init Applied" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Environment: ${{ (inputs.env != '' && inputs.env) || 'prod' }}" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Files:" >> "$GITHUB_STEP_SUMMARY"
          echo "- db/init/01_postgis.sql" >> "$GITHUB_STEP_SUMMARY"
          echo "- db/init/03_well_reports_fix.sql" >> "$GITHUB_STEP_SUMMARY"
          if [ -s data/tmp/sdr_raw_schema.sql ]; then echo "- (from snapshot) data/tmp/sdr_raw_schema.sql" >> "$GITHUB_STEP_SUMMARY"; fi
          echo "- db/init/03_sdr_children.sql" >> "$GITHUB_STEP_SUMMARY"
          if [ -f db/init/04_indexes.sql ]; then echo "- db/init/04_indexes.sql" >> "$GITHUB_STEP_SUMMARY"; fi
          if [ -f db/init/04_alerts.sql ]; then echo "- db/init/04_alerts.sql" >> "$GITHUB_STEP_SUMMARY"; fi
