name: ETL Nightly (P4)

on:
  schedule:
    - cron: '27 4 * * *'
  workflow_dispatch:
    inputs:
      env:
        description: Environment to target
        required: true
        default: dev
        type: choice
        options: [dev, staging, prod]

permissions:
  contents: read

concurrency:
  group: etl-${{ inputs.env || 'dev' }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Install deps
        run: |
          pip install -r apps/api/requirements.txt
          pip install psycopg2-binary
          pip install requests
      - name: Fetch SDR raw (R2 or Web)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STORAGE_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          RAW_SDR_BUCKET: ${{ vars.RAW_SDR_BUCKET }}
          RAW_SDR_PREFIX: ${{ vars.RAW_SDR_PREFIX }}
          STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
          SDR_ZIP_URL: ${{ secrets.SDR_ZIP_URL }}
          SDR_BASE_URL: ${{ secrets.SDR_BASE_URL || vars.SDR_BASE_URL }}
        run: |
          set -euo pipefail
          mkdir -p data/raw_data/SDRDownload/SDRDownload
          if [ -n "${RAW_SDR_BUCKET:-}" ]; then
            aws s3 sync "s3://${RAW_SDR_BUCKET}/${RAW_SDR_PREFIX}" "data/raw_data/SDRDownload/SDRDownload" --endpoint-url "${STORAGE_ENDPOINT}" --no-progress
            echo "RAW_SDR_DIR=$GITHUB_WORKSPACE/data/raw_data/SDRDownload/SDRDownload" >> "$GITHUB_ENV"
          elif [ -n "${SDR_ZIP_URL:-}" ] || [ -n "${SDR_BASE_URL:-}" ]; then
            echo "Attempting SDR web fetch..."
            python -c "import os; from data.sources.sdr_web_fetch import ensure_sdr_from_web as f; d='data/raw_data/SDRDownload/SDRDownload'; f(dest_dir=d, zip_url=os.environ.get('SDR_ZIP_URL'), base_url=os.environ.get('SDR_BASE_URL')); print('Downloaded SDR to', d)"
            ls -la data/raw_data/SDRDownload/SDRDownload || true
            ls -la data/raw_data/SDRDownload/SDRDownload/SDRDownload || true
            echo "RAW_SDR_DIR=$GITHUB_WORKSPACE/data/raw_data/SDRDownload/SDRDownload" >> "$GITHUB_ENV"
          else
            echo "No RAW_SDR_BUCKET or SDR_ZIP_URL/SDR_BASE_URL provided; skipping SDR fetch"
          fi
      - name: Run nightly snapshots
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PYTHONPATH: ${{ github.workspace }}
          SDR_ZIP_URL: ${{ secrets.SDR_ZIP_URL }}
          SDR_BASE_URL: ${{ secrets.SDR_BASE_URL || vars.SDR_BASE_URL }}
        run: |
          python -m data.jobs.nightly_snapshots
      - name: Summaries (Python)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python -c "import os, psycopg2; url=os.environ['DATABASE_URL']; conn=psycopg2.connect(url); cur=conn.cursor(); [ (cur.execute('SELECT COUNT(*) FROM ' + t), __import__('builtins').print('%s: %s' % (t, cur.fetchone()[0])) ) for t in ('well_reports','gwdb_wells','well_links') ]; cur.close(); conn.close()"


