name: ETL Nightly (P4)

on:
  schedule:
    - cron: '27 4 * * *'
  workflow_dispatch:
    inputs:
      env:
        description: Environment to target
        required: true
        default: dev
        type: choice
        options: [dev, staging, prod]

permissions:
  contents: read

concurrency:
  group: etl-${{ inputs.env || 'dev' }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/api/requirements.txt
          pip install psycopg2-binary
      - name: Run nightly snapshots
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PYTHONPATH: ${{ github.workspace }}
          RAW_SDR_DIR: data/raw_data/SDRDownload/SDRDownload
          RAW_SDR_SHAPE: data/raw_data/SDRDB_well_locations
        run: |
          python -m data.jobs.nightly_snapshots
      - name: Summaries
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          psql "$DATABASE_URL" -c "SELECT COUNT(*) AS well_reports FROM well_reports;"
          psql "$DATABASE_URL" -c "SELECT COUNT(*) AS gwdb_wells FROM gwdb_wells;"
          psql "$DATABASE_URL" -c "SELECT COUNT(*) AS well_links FROM well_links;"


