name: GWDB Schema Doc

on:
  workflow_dispatch:

jobs:
  schema-doc:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Generate GWDB schema doc
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python ground_truth/tools/generate_schema_md.py --database-url "$DATABASE_URL" --schema gwdb_ground_truth --out docs/SCHEMA_GWDB.md
          echo "Generated docs/SCHEMA_GWDB.md"


